accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('login/', login_view, name='signin'),
    path('signup/', register_view, name='signup'),
    path('logout/', logout_view, name='signout'),
    path('profile/<str:username>', profile_view, name='profile'),
]

forum/urls.py
from django.contrib import admin
from django.urls import path, include
from home.views import home_view
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name="home"),
    path('post/', include('post.urls')),
    path('account/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from .views import *

app_name = 'post'

urlpatterns = [
    path('index/', post_index, name='index'),
    path('create/', post_create, name='create'),
    path('<slug:slug>/disable/', post_disable, name='disable'),
    path('<slug:slug>/update/', post_update, name='update'),
    path('<slug:slug>/delete/', post_delete, name='delete'),
    path('<slug:slug>', post_detail, name='detail'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render, HttpResponse

# Create your views here.


def home_view(request):
    if request.user.is_authenticated:
        context = {
            'name': 'ataner',
        }
    else:
        context = {
            'name': 'misafir',
        }
    return render(request, 'home.html', context)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Forum{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
{% include 'header.html' %}

{% include 'messages.html' %}

{% block body %}

{% endblock %}

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" role="banner">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">My Blog</a>
        <button class="navbar-toggler mb-2" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb- mb-lg-0">
                <form class="d-flex" method="get"><!-- search only works when ur in post/index -->
                    <input class="form-control me-2" type="text" value="{{ request.GET.q }}" name="q"
                           placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </ul>
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'post:index' %}">Posts</a>
                </li>
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'post:create' %}">Create</a>
                    </li>
                {% endif %}
                {% if not request.user.is_authenticated %}
                    <div class="nav-item dropdown ">
                        <div class="nav-link dropdown-toggle dropdown-menu-right" href="#" id="navbarDropdown" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            Account
                        </div>
                        <div class="dropdown-menu dropdown-bar-block dropdown-border" style="right:0" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'accounts:signin' %}">Sign In</a></li>
                            <li><a class="dropdown-item" href="{% url 'accounts:signup' %}">Sign Up</a></li>
                        </div>
                    </div>

                {% else %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            {{ request.user.username }}
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="/account/profile/{{ request.user.username }}">Profile</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="{% url 'accounts:signout' %}">Sign Out</a></li>
                        </ul>
                    </li>
                {% endif %}


            </ul>

        </div>
    </div>
</nav>

templates/home.html
{% extends 'base.html' %}

{% block title %}Home - {{ block.super }}{% endblock %}

{% block body %}

    homepage {{ user.username }}

{% endblock %}

templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            {{ message }}
        </div>
    {% endfor %}
{% endif %}